# Generated by Django 2.0.5 on 2018-05-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='test',
        ),
        migrations.AddField(
            model_name='loja',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
