# Generated by Django 2.0.5 on 2018-05-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20180524_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='senha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
