# Generated by Django 2.0.5 on 2018-05-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_signup_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
