# Generated by Django 2.0.5 on 2018-05-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_signup_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='username',
        ),
        migrations.AddField(
            model_name='signup',
            name='first_name',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='signup',
            name='last_name',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='signup',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
