# Generated by Django 2.0.5 on 2018-05-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantidade', models.IntegerField(default=1)),
                ('categoria', models.IntegerField(choices=[(1, 'Processadores'), (2, 'Memória RAM'), (3, 'Disco Rígido/SSD'), (4, 'Placa de Vídeo'), (5, 'Gabinete'), (6, 'Placa Mãe'), (7, 'Fonte')], default=1)),
            ],
        ),
    ]
