# Generated by Django 2.0.5 on 2018-05-24 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='quantidade',
        ),
    ]
