# Generated by Django 2.0.5 on 2018-05-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_produtos_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
