# Generated by Django 2.0.5 on 2018-05-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_auto_20180524_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Processadores'), (2, 'Memória RAM'), (3, 'Disco Rígido/SSD'), (4, 'Placa de Vídeo'), (5, 'Gabinete'), (6, 'Placa Mãe'), (7, 'Fonte')], default=1),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
