# Generated by Django 2.0.5 on 2018-05-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_auto_20180524_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
