# Generated by Django 2.0.5 on 2018-05-24 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_auto_20180524_0334'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='test',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='produtos',
            field=models.ManyToManyField(to='produtos.Produtos'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
