# Generated by Django 2.0.5 on 2018-05-25 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20180524_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='usuario',
        ),
    ]
