# Generated by Django 2.0.5 on 2018-05-25 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedidos_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='usuario',
        ),
    ]
