# Generated by Django 2.0.5 on 2018-05-26 01:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_remove_pedidos_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
