# Generated by Django 2.0.5 on 2018-05-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_auto_20180526_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
