# Generated by Django 2.0.5 on 2018-05-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='test',
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='senha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
