# Generated by Django 2.0.5 on 2018-05-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
