# Generated by Django 2.0.5 on 2018-05-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountModel',
            new_name='SignupModel',
        ),
    ]
