# Generated by Django 2.0.5 on 2018-05-27 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180525_1837'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginModel',
        ),
    ]
