# Generated by Django 2.0.5 on 2018-05-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_signupmodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
